import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import GlobalTheme from "@/utils/global-theme";
import Footer from "@/components/shared/footer";
import LeftNavigation from "@/components/shared/left-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = false;

  return (
    <html lang="en">
      <body className={`${inter.className} bg-bgColor flex`}>
        <GlobalTheme>
          {auth && <LeftNavigation />}
          <main className="flex flex-col w-full min-h-screen p-20">
            <section className="flex-1 overflow-y-auto">{children}</section>
            <Footer />
          </main>
        </GlobalTheme>
      </body>
    </html>
  );
}
